import { FC, ReactNode } from "react";

const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type ChildrenTyep = {
    children: ReactNode
};

const RootLayout: FC<ChildrenTyep> = ({ children }) => {
    return (
        <html lang="en">
            <body>
                {
                    children
                }
            </body>
        </html>
    );
}

export default RootLayout;

export {
    metadata
};